// messages.js
const messages = [
    "You are strong and resilient!",
    "May your day be filled with joy and laughter.",
    "Celebrate the amazing woman you are!",
    "Wishing you success in all your endeavors.",
    "You make the world a better place.",
    "Embrace your uniqueness with pride.",
    "Here's to strong women. May we know them, may we be them, may we raise them.",
    "Keep shining bright!",
    "Your strength is unmatched.",
    "May your dreams become a reality.",
    "You are capable of incredible things.",
    "Cheers to the trailblazers and game-changers!",
    "Radiate positivity and kindness.",
    "May your day be as beautiful as you are.",
    "Stand tall and be proud of who you are.",
    "You are an inspiration to many.",
    "Believe in yourself, for you are capable of greatness.",
    "Keep challenging the status quo!",
    "May your journey be filled with love and laughter.",
    "You are enough, just as you are.",
    "May your confidence shine through.",
    "Celebrate your achievements, big and small.",
    "Wishing you courage and strength.",
    "May you always follow your dreams.",
    "You are a force to be reckoned with!",
    "Cheers to strong, empowered women!",
    "Your resilience knows no bounds.",
    "May your day be as special as you are.",
    "Here's to the women who make a difference.",
    "Keep breaking barriers!",
    "You are loved and appreciated.",
    "May you always be surrounded by love and positivity.",
    "Your kindness has the power to change the world.",
    "Embrace the journey ahead.",
    "Celebrate the victories, both big and small.",
    "You are making a positive impact.",
    "May your heart be filled with gratitude.",
    "Wishing you happiness and fulfillment.",
    "You are a true inspiration.",
    "May your confidence soar to new heights.",
    "Keep being the incredible person you are.",
    "Here's to the women who lead with grace and strength.",
    "May you always find joy in the little things.",
    "Your determination is admirable.",
    "You are a beacon of light in the world.",
    "Celebrate your achievements and successes.",
    "May your spirit be unbreakable.",
    "Wishing you a day filled with love and positivity.",
    "You are a symbol of strength and resilience.",
    "May your dreams take flight.",
    "Keep shining your light.",
    "Cheers to the women who make a difference.",
    "You are a masterpiece in progress.",
    "May your journey be filled with love and laughter.",
    "Celebrate your uniqueness.",
    "You are capable of achieving anything you set your mind to.",
    "May your day be as special as you are.",
    "Here's to the women who inspire us every day!",
    "You are a force to be reckoned with.",
  ];
  
  export default messages;
  